# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_zybo2/design_zybo2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2 || ORIG_REF_NAME==design_zybo2} -quiet] -quiet

# IP: bd/design_zybo2/ip/design_zybo2_distance_zybo2_ip_0_0/design_zybo2_distance_zybo2_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2_distance_zybo2_ip_0_0 || ORIG_REF_NAME==design_zybo2_distance_zybo2_ip_0_0} -quiet] -quiet

# IP: bd/design_zybo2/ip/design_zybo2_processing_system7_0_0/design_zybo2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2_processing_system7_0_0 || ORIG_REF_NAME==design_zybo2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_zybo2/ip/design_zybo2_ps7_0_axi_periph_0/design_zybo2_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_zybo2_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_zybo2/ip/design_zybo2_rst_ps7_0_100M_0/design_zybo2_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_zybo2_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_zybo2/ip/design_zybo2_auto_pc_0/design_zybo2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_zybo2_auto_pc_0 || ORIG_REF_NAME==design_zybo2_auto_pc_0} -quiet] -quiet

# XDC: bd/design_zybo2/design_zybo2_ooc.xdc
