webtalk_init -webtalk_dir C:\\Users\\smelvinsky\\Desktop\\distance_zybo2\\distance_zybo2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-06-20 03:31:50" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "feq3v2quqofj12r6om947t1ns6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-7410 APU with AMD Radeon R5 Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2196 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.460 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1529456031189" -context "sdk\\\\bsp/1529456031189"
webtalk_add_data -client sdk -key hwid -value "1529346076399" -context "sdk\\\\bsp/1529456031189"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1529456031189"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1529456031189"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1529456031189"
webtalk_add_data -client sdk -key uid -value "1529456374598" -context "sdk\\\\bsp/1529456374598"
webtalk_add_data -client sdk -key hwid -value "1529346076399" -context "sdk\\\\bsp/1529456374598"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1529456374598"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1529456374598"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1529456374598"
webtalk_add_data -client sdk -key uid -value "1529456538777" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key hwid -value "1529346076399" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key bspid -value "1529456374598" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key projSize -value "600.69921875" -context "sdk\\\\application/1529456538777"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key BootgenCount -value "6" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key FlashCount -value "7" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1529458310061"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1529458310061"
webtalk_transmit -clientid 2279291359 -regid "" -xml C:\\Users\\smelvinsky\\Desktop\\distance_zybo2\\distance_zybo2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\smelvinsky\\Desktop\\distance_zybo2\\distance_zybo2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\smelvinsky\\Desktop\\distance_zybo2\\distance_zybo2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
